apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-canary
  labels:
    app: producer
    env: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
      env: canary
  template:
    metadata:
      labels:
        app: producer
        env: canary
    spec:
      containers:
      - name: benthos
        image: gcr.io/k8s-the-hard-way-277515/benthos-producer:1.0.0
        imagePullPolicy: Always
        env:
          - name: KAFKA_ADDR
            value: kafka-headless.kafka:9092
        ports:
          - containerPort: 4195
