apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: default
  labels:
    app: producer

spec:
  selector:
    app: producer
  type: ClusterIP
  ports:
    - name: producer-port
      port: 4195
      targetPort: 4195
