apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-production
  labels:
    app: producer
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
      env: production
  template:
    metadata:
      labels:
        app: producer
        env: production
    spec:
      containers:
      - name: benthos
        image: gcr.io/k8s-the-hard-way-277515/benthos-producer:1.0.0
        imagePullPolicy: Always
        env:
          - name: KAFKA_ADDR
            value: kafka-headless.kafka:9092
        ports:
          - containerPort: 4195
